### ISSUE TITLE
Support for Raspberry Pi 5 / Debian Bookworm

### ISSUE THREAD

**Issue by Epyc7** [retronas/retronas#390]
I managed to get RetroNAS working on the Pi 5 and Pi OS Lite (64-bit) Debian Bookworm (Pi 5 does not support Bullseye).  

However, I noticed some slight PS3 disc streaming hitches while playing games.

Does RetroNAS or ps3netserv need to be updated to support the latest?

**Comment by sairuk** [comment]
We pull the latest ps3netsrv during install time, so I'm not sure what you could mean otherwise by latest.

I doubt there is anything we need to do on our side in regards to this, I do not have an rpi5 to try and replicate any behaviour (no money/stock atm). although I have used bookworm to test our installers to make sure they are compatible. My main retronas unit is still rpi4 with bullseye, which I will roll to bookworm soon'ish.

as your situation is currently somewhat unique you'll need to try and debug further yourself, there is not enough data to show an issue with retronas and this should be raised as a discussion until there is some actionable data to show there is an issue we can work on. When you do so probably best to include network type, speed metrics, storage types if there was an rpi4 in the mix before etc in the mix

https://github.com/orgs/retronas/discussions
